#define FRAME_SIZE_PIXELS  16
#define GAME_WIDTH_PIXELS  256
#define GAME_HEIGHT_PIXELS 144
#define GAME_WIDTH         (GAME_WIDTH_PIXELS  / FRAME_SIZE_PIXELS)
#define GAME_HEIGHT        (GAME_HEIGHT_PIXELS / FRAME_SIZE_PIXELS)
#define GAME_SCALE         3
#define WINDOW_WIDTH       (GAME_WIDTH_PIXELS  * GAME_SCALE)
#define WINDOW_HEIGHT      (GAME_HEIGHT_PIXELS * GAME_SCALE)

#define QUAD_CAPACITY   1000
#define INDEX_CAPACITY  (QUAD_CAPACITY * 6)
#define VERTEX_CAPACITY (QUAD_CAPACITY * 4)
