#define FRAME_SIZE_PIXELS  16
#define GAME_WIDTH_PIXELS  160
#define GAME_HEIGHT_PIXELS 144
#define GAME_WIDTH         (GAME_WIDTH_PIXELS  / FRAME_SIZE_PIXELS)
#define GAME_HEIGHT        (GAME_HEIGHT_PIXELS / FRAME_SIZE_PIXELS)
#define GAME_SCALE         4
#define WINDOW_WIDTH       (GAME_WIDTH_PIXELS  * GAME_SCALE)
#define WINDOW_HEIGHT      (GAME_HEIGHT_PIXELS * GAME_SCALE)

#define HUD_WIDTH  GAME_WIDTH
#define HUD_HEIGHT 1

#define CAMERA_WIDTH  GAME_WIDTH
#define CAMERA_HEIGHT (GAME_HEIGHT - HUD_HEIGHT)

#define UP    0x01
#define LEFT  0x02
#define DOWN  0x04
#define RIGHT 0x08

#define QUAD_CAPACITY   1000
#define INDEX_CAPACITY  (QUAD_CAPACITY * 6)
#define VERTEX_CAPACITY (QUAD_CAPACITY * 4)

#define SPRITE_CAPACITY 32

#define BLOCKS_CAPACITY 32
